config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.sign_board

  root 'static_pages#home'
  resources :static_pages do
    collection do
      get :get_search_prefecture_link
      get :get_search_municipality_link
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'restaurants#new'
  delete '/signout', to: 'restaurants#destroy'

  get '/restaurants/:id/activation', to: 'restaurants#activation', as: :activation
  
  resources :restaurants do
    collection do
      get :search
      get :search_from_prefecture
      get :search_from_municipality
      get :search_from_budget
      get :get_search_prefecture_link
      get :get_search_municipality_link
      get :get_municipality_form
    end
    member do
      get :get_menu
      get :get_picture
    end
  end
  resources :restaurants,     only: [:new, :show, :index, :edit, :update, :create, :destroy, :activation]
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :restaurant, path: config[:restaurant][:path] do
    resources :messages, only: [:new, :show, :index, :create, :destroy], as: :message, controller: :messages
    resources :pictures, only: [:new, :edit, :update, :create, :destroy], as: :picture, controller: :pictures
    resources :menus, only: [:new, :edit, :update, :create, :destroy], as: :menu, controller: :menus
    resources :courses, only: [:new, :edit, :update, :create, :destroy], as: :course, controller: :courses
  end


  get '*anything' => 'errors#routing_error'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :password_reset_token, :address3

  belongs_to :category, class_name: "Category", foreign_key: 'category_id'
  belongs_to :prefecture, class_name: "Prefecture", foreign_key: 'prefecture_id'
  belongs_to :municipality, class_name: "Municipality", foreign_key: 'municipality_id'
  has_many :messages, dependent: :destroy
  has_many :pictures, class_name: "RestaurantPicture", dependent: :destroy
  has_many :menus, class_name: "RestaurantMenu", dependent: :destroy
  has_many :courses, class_name: "RestaurantCourse", dependent: :destroy

  geocoded_by      :address
  after_validation :geocode
  reverse_geocoded_by :latitude, :longitude

  before_save :downcase_email
  before_validation :create_address

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false },
                    allow_nil: true
  validates :password, presence:true, length:{ minimum: 6, maximum: 20 }, allow_nil: true
  validates :profile,         length:{ maximum: 800 }
  validates :phone_number,    length:{ maximum: 100 }
  validates :address,         length:{ maximum: 100 }
  validates :business_hours,  length:{ maximum: 100 }
  validates :regular_holiday, length:{ maximum: 100 }
  validates :home_page,       length:{ maximum: 100 }
  validates :morning_budget, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :noon_budget, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :night_budget, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :image_size

  mount_uploader :image, RestaurantImageUploader

  has_secure_password
    class << self
    #渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    #ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  #永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = Restaurant.new_token
    update_attribute(:remember_digest, Restaurant.digest(remember_token))
  end

  #ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  #有効化用のメールを送信する
  def send_activation_email
    create_activation_digest
    RestaurantMailer.account_activation(self).deliver_now
  end


  #パスワード再設定のメールを送信する
  def send_password_reset_email
    create_password_reset_digest
    RestaurantMailer.password_reset(self).deliver_now
  end

  #アカウントを有効にする
  def activate
    update_columns(activated: true)
  end

  #パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    self.password_reset_sent_at < 2.hours.ago
  end


  #渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
    # アップロードされた画像のサイズをバリデーションする
    def image_size
      if image.size > 3.megabytes
        errors.add(:image, "3MB以上の画像はアップロードできません")
      end
    end

    def downcase_email
      email.downcase!
    end

    def create_address
      #市区町村
      municipalitiy = self.municipality
      prefecture = municipalitiy.prefecture
      self.address = "#{prefecture.name}#{municipalitiy.name}#{self.address3}"
    end

    #パスワード再設定用の属性を設定する
    def create_password_reset_digest
      self.password_reset_token = Restaurant.new_token
      update_columns(password_reset_digest: Restaurant.digest(self.password_reset_token),
                     password_reset_sent_at: Time.zone.now)
    end

    #有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token = Restaurant.new_token
      update_attribute(:activation_digest, Restaurant.digest(activation_token))
    end
end

app/controllers/restaurant/courses_controller.rb
class Restaurant::CoursesController < ApplicationController
  before_action :authenticate, only: [:new, :edit, :update, :create, :destroy]

  def new
    @restaurant_course = @current_restaurant.courses.build
  end

  def edit
  end

  def create
    @restaurant_course = @current_restaurant.courses.build(restaurant_course_params)
    if @restaurant_course.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  private
    def restaurant_course_params
      params.require(:restaurant_course).permit(
        :name, :price, :time_limit, :people_num, :bottomless,
        :content, :notes
      )
    end
end

app/controllers/restaurant/menus_controller.rb
class Restaurant::MenusController < ApplicationController
  before_action :authenticate, only: [:new, :edit, :update, :create, :destroy]

  def new
    @restaurant_menu = @current_restaurant.menus.build
  end

  def edit
  end

  def create
    @restaurant_menu = @current_restaurant.menus.build(restaurant_menu_params)
    if @restaurant_menu.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  private
    def restaurant_menu_params
      params.require(:restaurant_menu).permit(
        :name, :price, :type_id
      )
    end
end

app/controllers/restaurant/messages_controller.rb
class Restaurant::MessagesController < ApplicationController
  before_action :set_message, only: [:show, :destroy]
  before_action :authenticate, only: [:new, :create, :destroy]

  def index
    @messages = Message.all
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if (@message.restaurant.id == @current_restaurant.id) && @message.save
      flash[:success] = "メッセ―ジを送信しました"
      redirect_to root_url
    else
      flash[:warning] = "送信に失敗しました"
      render 'new'
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(
        :restaurant_id, :image, :text
      )
    end
end

app/controllers/restaurant/pictures_controller.rb
class Restaurant::PicturesController < ApplicationController
  before_action :authenticate, only: [:new, :edit, :update, :create, :destroy]

  def new
    @restaurant_picture = @current_restaurant.pictures.build
  end

  def edit
  end

  def create
    @restaurant_picture = @current_restaurant.pictures.build(restaurant_picture_params)
    if @restaurant_picture.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  private
    def restaurant_picture_params
      params.require(:restaurant_picture).permit(
        :title, :picture, :type_id
      )
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:get_menu, :get_picture, :show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all.includes(:category)
    @search_form = Restaurant::SearchForm.new
  end

  def search
    @search_form = Restaurant::SearchForm.new(search_form_params)
    @restaurants = @search_form.search
    render 'index'
  end

  def get_search_prefecture_link
    respond_to do |format|
      format.html
      format.js
    end
    render 'restaurants/index/search_prefecture_link'
  end

  def get_search_municipality_link
    prefecture_id = params[:prefecture_id]
    @prefecture = Prefecture.find(prefecture_id)
    @municipalities = @prefecture.municipalities
    respond_to do |format|
      format.html
      format.js
    end
    render 'restaurants/index/search_municipality_link'
  end

  def search_from_municipality
    @restaurants = Restaurant.find_by(municipality_id: params[:municipality_id])
    @search_form = Restaurant::SearchForm.new
    render 'index'
  end

  def search_from_prefecture
    @restaurants = Restaurant.find_by(prefecture_id: params[:prefecture_id])
    @search_form = Restaurant::SearchForm.new
    render 'index'
  end

  def search_from_budget
    @restaurants = Restaurant.where('budget > ?', 1)
    @restaurants.each do |r|
      puts r.budget
    end
    @search_form = Restaurant::SearchForm.new
    render 'index'
  end

  def get_municipality_form
    prefecture_id = params[:prefecture_id]
    prefecture = Prefecture.find(prefecture_id)
    @municipalities = prefecture.municipalities
    respond_to do |format|
      format.html
      format.js
    end
    render 'municipality_form'
  end

  def get_menu
    type_id = params[:type_id]
    @menus = @restaurant.menus.where(type_id: type_id)
    respond_to do |format|
      format.html { redirect_to @restaurant }
      format.js
    end
    render 'menu'
  end

  def get_picture
    type_id = params[:type_id]
    if '0' == type_id
      @pictures = @restaurant.pictures.all
    else
      @pictures = @restaurant.pictures.where(type_id: type_id)
    end
    respond_to do |format|
      format.html { redirect_to @restaurant }
      format.js
    end
    render 'picture'
  end

  def show
    @messages = @restaurant.messages.includes(:restaurant).order(created_at: :desc)
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      @restaurant.send_activation_email
      flash[:success] = "メールを送信しました。アカウントを有効化してください"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  def activation
    @restaurant = Restaurant.find_by(email: params[:email])
    if @restaurant && !@restaurant.activated? && @restaurant.authenticated?(:activation, params[:id])
      @restaurant.activate
      login @restaurant
      flash[:success] = "アカウントを有効化しました"
      redirect_to root_url
    else
      flash[:danger] = "無効なアクティべーションリンクです"
      redirect_to root_url
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(
        :name, :category_id, :image, :email, :profile, :phone_number,
        :prefecture_id, :municipality_id, :address3, :business_hours, :regular_holiday,
        :morning_budget, :noon_budget, :night_budget,
        :home_page, :password, :password_confirmation
      )
    end

    def search_form_params
      params.require(:restaurant_search_form).permit(
        :name, :category_id, :latitude, :longitude, :radius
      )
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true, class: 'restaurant_form container custom-form-container') do |form| %>
<p><font class="asterisk">＊</font>が付いている項目は入力必須です</p>

  <% form.object.errors.messages[:name].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '店名' + e %>
    </div>
  <% end %>
  <div class="name">
    <label>店名<font class="asterisk">＊</font></label>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <% form.object.errors.messages[:category].each do |e| %>
    <div class="alert alert-danger">
      <li><%= 'カテゴリ' + e %>
    </div>
  <% end %>
  <div class="category_id">
    <label>カテゴリー<font class="asterisk">＊</font></label>
    <%= form.collection_select :category_id, Category.all, :id, :name, {}, class: 'form-control', required: true %>
  </div>

  <% form.object.errors.messages[:image].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '画像' + e %>
    </div>
  <% end %>
  <div class="image">
    <label>画像</label>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <% form.object.errors.messages[:email].each do |e| %>
    <div class="alert alert-danger">
      <li><%= 'メールアドレス' + e %>
    </div>
  <% end %>
  <div class="email">
    <label>メールアドレス<font class="asterisk">＊</font></label>
    <%= form.text_field :email, class: 'form-control', required: true %>
  </div>

  <% form.object.errors.messages[:address].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '住所' + e %>
    </div>
  <% end %>
  <div class="address" id="address_form">
    <label>住所</label>
    <div class="form-row">
      <% Prefecture.all.each do |p| %>
        <%= link_to "#{p.name}", get_municipality_form_restaurants_path(prefecture_id: p.id), remote: true, id: "municipality_form_request#{p.id}", hidden: true %>
      <% end %>
      <div class="form-group col-sm-2">
        <%= form.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, class: 'form-control', id: 'prefecture_form' %>
      </div>
      <div class="form-group col-sm-4" id="municipality_form">
        <%= form.collection_select :municipality_id, Prefecture.first.municipalities, :id, :name, {}, class: 'form-control' %>
      </div>
      <div class="form-group col-sm-6">
        <%= form.text_field :address3, class: 'form-control', placeholder: '〇〇町△△丁目 123-45' %>
      </div>
    </div>
  </div>

  <% form.object.errors.messages[:phone_number].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '電話番号' + e %>
    </div>
  <% end %>
  <div class="phone_number">
    <label>電話番号</label>
    <%= form.text_field :phone_number, class: 'form-control' %>
  </div>

  <% form.object.errors.messages[:business_hours].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '営業時間' + e %>
    </div>
  <% end %>
  <div class="business_hours">
    <label>営業時間</label>
    <%= form.text_field :business_hours, class: 'form-control', placeholder: '昼 11:00 ~ 14:00     夜 17:00 ~ 22:00' %>
  </div>

  <% form.object.errors.messages[:regular_holiday].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '定休日' + e %>
    </div>
  <% end %>
  <div class="regular_holiday">
    <label>定休日</label>
    <%= form.text_field :regular_holiday, class: 'form-control', placeholder: '毎週水曜日' %>
  </div>

  <% form.object.errors.messages[:morning_budget].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '予算(朝)' + e %>
    </div>
  <% end %>
  <% form.object.errors.messages[:noon_budget].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '予算(昼)' + e %>
    </div>
  <% end %>
  <% form.object.errors.messages[:night_budget].each do |e| %>
    <div class="alert alert-danger">
      <li><%= '予算(夜)' + e %>
    </div>
  <% end %>
  <div class="budget">
    <label>予算</label>
    <div class="budgets">
      <label>朝</label>
      <%= form.number_field :morning_budget, min:0, class: 'form-control', placeholder: '500' %>
      <label>昼</label>
      <%= form.number_field :noon_budget, min:0, class: 'form-control', placeholder: '700' %>
      <label>夜</label>
      <%= form.number_field :night_budget, min:0, class: 'form-control', placeholder: '2000' %>
    </div>
  </div>

  <% form.object.errors.messages[:home_page].each do |e| %>
    <div class="alert alert-danger">
      <li><%= 'ホームページ' + e %>
    </div>
  <% end %>
  <div class="home_page">
    <label>ホームページ</label>
    <%= form.text_field :home_page, class: 'form-control' %>
  </div>

  <% form.object.errors.messages[:password].each do |e| %>
    <div class="alert alert-danger">
      <li><%= 'パスワード' + e %>
    </div>
  <% end %>
  <div class="password">
    <label>パスワード<font class="asterisk">＊</font></label>
    <%= form.password_field :password, class: 'form-control', required: true %>
  </div>

  <% form.object.errors.messages[:password_confirmation].each do |e| %>
    <div class="alert alert-danger">
      <li><%= 'パスワード確認' + e %>
    </div>
  <% end %>
  <div class="password_confirmation">
    <label>パスワード確認<font class="asterisk">＊</font></label>
    <%= form.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>

  <% form.object.errors.messages[:profile].each do |e| %>
    <div class="alert alert-danger">
      <li><%= 'プロフィール' + e %>
    </div>
  <% end %>
  <div class="profile">
    <label>プロフィール</label>
    <%= form.text_area :profile, class: 'form-control', placeholder: '800字以内でご記入ください' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<div id="test">
</div>

<script type="text/javascript">
  var prefecture_form = document.getElementById("prefecture_form");

  prefecture_form.onchange = function(){
    console.log(prefecture_form.value);

    var municipality_form_request = document.getElementById("municipality_form_request" + prefecture_form.value);
    municipality_form_request.click();
  }
</script>

app/views/restaurants/_menu.html.erb
<% if @menus.present? %>
  <div class="menus">
    <label class="type_name"><%= @menus.first.type.name %></label>
    <% @menus.each do |m| %>
      <div class="menu">
        <p><span class="name"><%= m.name %></span><span class="price"><%= m.price %>円</span>
      </div>
    <% end %>
  </div>
<% end %>

app/views/restaurants/_municipality_form.html.erb
<%= select :restaurant, :municipality_id, @municipalities.map{|t| [t.name, t.id]}, {}, class: 'form-control' %>

app/views/restaurants/_picture.html.erb
<% if @pictures.present? %>
  <div class="pictures">
    <label class="type_name"><%= @pictures.first.type.name %></label>
    <% @pictures.each do |p| %>
      <div class="picture">
        <div class="image">
          <%= image_tag p.picture_url if p.picture_url %>
        </div>
        <p class="title"><%= p.title %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<%= link_to(restaurant_path(restaurant)) do %>
  <div class="restaurant">
    <div class="image">
      <%= image_tag restaurant.image_url if restaurant.image_url %>
    </div>
  
    <h1 class="name">
      <span><%= restaurant.name %></span>
    </h1>
    <label class="category">
      <%= restaurant.category.name %>
    </label>
  
    <div class="profile">
      <p><%= simple_format(restaurant.profile) %></p>
    </div>
  </div>
<% end %>

app/views/restaurants/_sideber.html.erb
<div class="sideber">
  <div id="search_from_place">
    <%= check_box_tag 'search_from_place_checkbox', 'value', false, class: 'display_switch_button' %>
    <label class="button" for="search_from_place_checkbox">都道府県から探す</label>
    <div class="search_from_place_links" id="search_from_place_links">
      <%= render 'restaurants/index/search_prefecture_link' %>
    </div>
  </div>
  <div id="search_from_budget">
    <%= check_box_tag 'search_from_budget_checkbox', 'value', false, class: 'display_switch_button' %>
    <label class="button" for="search_from_budget_checkbox">予算から探す</label>
    <div class="search_from_budget" id="search_from_budget">
      <span><%= link_to "予算", search_from_budget_restaurants_path, class: 'link' %></span>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="top_search_form">
    <%= render 'shared/search_form' %>
  </div>
  <div class="row">
    <div class="col-sm-5 col-md-4 side_search_form">
      <%= render 'restaurants/sideber' %>
    </div>
    <div class="col-sm-7 col-md-8">
      <div class="restaurants">
        <% if @restaurants.present? %>
          <%= render @restaurants %>
        <% else %>
          <p class="msg">検索にヒットしませんでした
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/menu.js.erb
$("#drop_down_content").html("<%= escape_javascript(render('restaurants/menu')) %>");

app/views/restaurants/municipality_form.js.erb
$("#municipality_form").html("<%= escape_javascript(render('restaurants/municipality_form')) %>");

app/views/restaurants/new.html.erb
<div class="container">
  <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/picture.js.erb
$("#drop_down_content").html("<%= escape_javascript(render('restaurants/picture')) %>");

app/views/restaurants/show.html.erb
<div class="show_restaurant container">
  <div class="image">
    <%= image_tag @restaurant.image_url if @restaurant.image_url %>
  </div>

  <h1 class="name">
    <span><%= @restaurant.name %></span>
  </h1>
  <label class="category">
    <%= @restaurant.category.name %>
  </label>

  <div class="profile">
    <td><%= simple_format(@restaurant.profile) %>
  </div>

  <%= render 'restaurants/shows/drop_down' %>

  <label class="info_label">店舗情報</label>
  <table class="text_base_info">
    <tr class="phone_number">
      <th><label>電話番号</label></th>
      <td><span><%= @restaurant.phone_number %></span></td>
    </tr>
    
    <tr class="address">
      <th><label>住所</label></th>
      <td><span><%= @restaurant.address %></span></td>
    </tr>
    
    <tr class="business_hours">
      <th><label>営業時間</label></th>
      <td><span><%= @restaurant.business_hours %></span></td>
    </tr>
    
    <tr class="regular_holiday">
      <th><label>定休日</label></th>
      <td><span><%= @restaurant.regular_holiday %></span></td>
    </tr>
    
    <tr class="budget">
      <th><label>予算</label></th>
      <td>
        <span>朝<%= @restaurant.morning_budget if @restaurant.morning_budget.present? %></span><br>
        <span>朝<%= @restaurant.noon_budget if @restaurant.noon_budget.present? %></span><br>
        <span>朝<%= @restaurant.night_budget if @restaurant.night_budget.present? %></span>
      </td>
    </tr>
    
    <tr class="home_page">
      <th><label>HP</label></th>
      <td><span><%= @restaurant.home_page %></span></td>
    </tr>
  </table>
  <% if @restaurant.latitude.present? && @restaurant.longitude.present? %>
    <%= render 'restaurants/shows/map' %>
  <% end %>
</div>

<script type="text/javascript">
  if(<%= @restaurant.latitude %> != null && <%= @restaurant.longitude %> != null){
    function initMap() {
      var restaurant ={lat: <%= @restaurant.latitude %>, lng: <%= @restaurant.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: restaurant
      });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);
  
      var contentString = '住所：<%= @address %>';
      var infowindow = new google.maps.InfoWindow({
          content: contentString
      });
  
      var marker = new google.maps.Marker({
          position: restaurant,
          map: map,
          title: contentString
      });
  
      marker.addListener('click', function() {
          infowindow.open(map, marker);
      });
    }
  }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyC8l2Eh8zAtS62Lw8hY1mU-iO68Gaw9C6Y&callback=initMap">
</script>