config/routes.rb
Rails.application.routes.draw do
  config = Rails.application.config.sign_board

  root 'static_pages#home'
  resources :static_pages do
    collection do
      get :get_search_prefecture_link
      get :get_search_municipality_link
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'restaurants#new'
  delete '/signout', to: 'restaurants#destroy'

  get '/restaurants/:id/activation', to: 'restaurants#activation', as: :activation
  
  resources :restaurants do
    collection do
      get :search
      get :search_from_prefecture
      get :search_from_municipality
      get :search_from_budget
      get :get_search_prefecture_link
      get :get_search_municipality_link
      get :get_municipality_form
    end
    member do
      get :get_menu
      get :get_picture
    end
  end
  resources :restaurants,     only: [:new, :show, :index, :edit, :update, :create, :destroy, :activation]
  resources :password_resets, only: [:new, :create, :edit, :update]

  namespace :restaurant, path: config[:restaurant][:path] do
    resources :messages, only: [:new, :show, :index, :create, :destroy], as: :message, controller: :messages
    resources :pictures, only: [:new, :edit, :update, :create, :destroy], as: :picture, controller: :pictures
    resources :menus, only: [:new, :edit, :update, :create, :destroy], as: :menu, controller: :menus
    resources :courses, only: [:new, :edit, :update, :create, :destroy], as: :course, controller: :courses
  end


  get '*anything' => 'errors#routing_error'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :password_reset_token, :address3

  belongs_to :category, class_name: "Category", foreign_key: 'category_id'
  belongs_to :prefecture, class_name: "Prefecture", foreign_key: 'prefecture_id'
  belongs_to :municipality, class_name: "Municipality", foreign_key: 'municipality_id'
  has_many :messages, dependent: :destroy
  has_many :pictures, class_name: "RestaurantPicture", dependent: :destroy
  has_many :menus, class_name: "RestaurantMenu", dependent: :destroy
  has_many :courses, class_name: "RestaurantCourse", dependent: :destroy

  geocoded_by      :address
  after_validation :geocode
  reverse_geocoded_by :latitude, :longitude

  before_save :downcase_email
  before_validation :create_address

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false },
                    allow_nil: true
  validates :password, presence:true, length:{ minimum: 6, maximum: 20 }, allow_nil: true
  validates :profile,         length:{ maximum: 800 }
  validates :phone_number,    length:{ maximum: 100 }
  validates :address,         length:{ maximum: 100 }
  validates :business_hours,  length:{ maximum: 100 }
  validates :regular_holiday, length:{ maximum: 100 }
  validates :home_page,       length:{ maximum: 100 }
  validates :morning_budget, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :noon_budget, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :night_budget, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :image_size

  mount_uploader :image, RestaurantImageUploader

  has_secure_password
    class << self
    #渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    #ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  #永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = Restaurant.new_token
    update_attribute(:remember_digest, Restaurant.digest(remember_token))
  end

  #ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  #有効化用のメールを送信する
  def send_activation_email
    create_activation_digest
    RestaurantMailer.account_activation(self).deliver_now
  end


  #パスワード再設定のメールを送信する
  def send_password_reset_email
    create_password_reset_digest
    RestaurantMailer.password_reset(self).deliver_now
  end

  #アカウントを有効にする
  def activate
    update_columns(activated: true)
  end

  #パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    self.password_reset_sent_at < 2.hours.ago
  end


  #渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  private
    # アップロードされた画像のサイズをバリデーションする
    def image_size
      if image.size > 3.megabytes
        errors.add(:image, "3MB以上の画像はアップロードできません")
      end
    end

    def downcase_email
      email.downcase!
    end

    def create_address
      #市区町村
      municipalitiy = self.municipality
      prefecture = municipalitiy.prefecture
      self.address = "#{prefecture.name}#{municipalitiy.name}#{self.address3}"
    end

    #パスワード再設定用の属性を設定する
    def create_password_reset_digest
      self.password_reset_token = Restaurant.new_token
      update_columns(password_reset_digest: Restaurant.digest(self.password_reset_token),
                     password_reset_sent_at: Time.zone.now)
    end

    #有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token = Restaurant.new_token
      update_attribute(:activation_digest, Restaurant.digest(activation_token))
    end
end

app/controllers/restaurant/courses_controller.rb
class Restaurant::CoursesController < ApplicationController
  before_action :authenticate, only: [:new, :edit, :update, :create, :destroy]

  def new
    @restaurant_course = @current_restaurant.courses.build
  end

  def edit
  end

  def create
    @restaurant_course = @current_restaurant.courses.build(restaurant_course_params)
    if @restaurant_course.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  private
    def restaurant_course_params
      params.require(:restaurant_course).permit(
        :name, :price, :time_limit, :people_num, :bottomless,
        :content, :notes
      )
    end
end

app/controllers/restaurant/menus_controller.rb
class Restaurant::MenusController < ApplicationController
  before_action :authenticate, only: [:new, :edit, :update, :create, :destroy]

  def new
    @restaurant_menu = @current_restaurant.menus.build
  end

  def edit
  end

  def create
    @restaurant_menu = @current_restaurant.menus.build(restaurant_menu_params)
    if @restaurant_menu.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  private
    def restaurant_menu_params
      params.require(:restaurant_menu).permit(
        :name, :price, :type_id
      )
    end
end

app/controllers/restaurant/messages_controller.rb
class Restaurant::MessagesController < ApplicationController
  before_action :set_message, only: [:show, :destroy]
  before_action :authenticate, only: [:new, :create, :destroy]

  def index
    @messages = Message.all
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if (@message.restaurant.id == @current_restaurant.id) && @message.save
      flash[:success] = "メッセ―ジを送信しました"
      redirect_to root_url
    else
      flash[:warning] = "送信に失敗しました"
      render 'new'
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(
        :restaurant_id, :image, :text
      )
    end
end

app/controllers/restaurant/pictures_controller.rb
class Restaurant::PicturesController < ApplicationController
  before_action :authenticate, only: [:new, :edit, :update, :create, :destroy]

  def new
    @restaurant_picture = @current_restaurant.pictures.build
  end

  def edit
  end

  def create
    @restaurant_picture = @current_restaurant.pictures.build(restaurant_picture_params)
    if @restaurant_picture.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  private
    def restaurant_picture_params
      params.require(:restaurant_picture).permit(
        :title, :picture, :type_id
      )
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:get_menu, :get_picture, :show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all.includes(:category)
    @search_form = Restaurant::SearchForm.new
  end

  def search
    @search_form = Restaurant::SearchForm.new(search_form_params)
    @restaurants = @search_form.search
    render 'index'
  end

  def get_search_prefecture_link
    respond_to do |format|
      format.html
      format.js
    end
    render 'restaurants/index/search_prefecture_link'
  end

  def get_search_municipality_link
    prefecture_id = params[:prefecture_id]
    @prefecture = Prefecture.find(prefecture_id)
    @municipalities = @prefecture.municipalities
    respond_to do |format|
      format.html
      format.js
    end
    render 'restaurants/index/search_municipality_link'
  end

  def search_from_municipality
    @restaurants = Restaurant.find_by(municipality_id: params[:municipality_id])
    @search_form = Restaurant::SearchForm.new
    render 'index'
  end

  def search_from_prefecture
    @restaurants = Restaurant.find_by(prefecture_id: params[:prefecture_id])
    @search_form = Restaurant::SearchForm.new
    render 'index'
  end

  def search_from_budget
    @restaurants = Restaurant.where('budget > ?', 1)
    @restaurants.each do |r|
      puts r.budget
    end
    @search_form = Restaurant::SearchForm.new
    render 'index'
  end

  def get_municipality_form
    prefecture_id = params[:prefecture_id]
    prefecture = Prefecture.find(prefecture_id)
    @municipalities = prefecture.municipalities
    respond_to do |format|
      format.html
      format.js
    end
    render 'municipality_form'
  end

  def get_menu
    type_id = params[:type_id]
    @menus = @restaurant.menus.where(type_id: type_id)
    respond_to do |format|
      format.html { redirect_to @restaurant }
      format.js
    end
    render 'menu'
  end

  def get_picture
    type_id = params[:type_id]
    if '0' == type_id
      @pictures = @restaurant.pictures.all
    else
      @pictures = @restaurant.pictures.where(type_id: type_id)
    end
    respond_to do |format|
      format.html { redirect_to @restaurant }
      format.js
    end
    render 'picture'
  end

  def show
    @messages = @restaurant.messages.includes(:restaurant).order(created_at: :desc)
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      @restaurant.send_activation_email
      flash[:success] = "メールを送信しました。アカウントを有効化してください"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if logged_in?
      @current_restaurant.delete
      logout
      flash[:success] = "退会完了しました"
    else
      flash[:warning] = "ログインしていないため退会できません"
    end
    redirect_to root_url
  end

  def activation
    @restaurant = Restaurant.find_by(email: params[:email])
    if @restaurant && !@restaurant.activated? && @restaurant.authenticated?(:activation, params[:id])
      @restaurant.activate
      login @restaurant
      flash[:success] = "アカウントを有効化しました"
      redirect_to root_url
    else
      flash[:danger] = "無効なアクティべーションリンクです"
      redirect_to root_url
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(
        :name, :category_id, :image, :email, :profile, :phone_number,
        :prefecture_id, :municipality_id, :address3, :business_hours, :regular_holiday,
        :morning_budget, :noon_budget, :night_budget,
        :home_page, :password, :password_confirmation
      )
    end

    def search_form_params
      params.require(:restaurant_search_form).permit(
        :name, :category_id, :latitude, :longitude, :radius
      )
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/index/_search_municipality_link.html.erb
<p class="title"><%= link_to "<<戻る", get_search_prefecture_link_restaurants_path, remote: true %></p>
<div class="search_prefecture_link">
  <p><%= link_to "#{@prefecture.name}", search_from_prefecture_restaurants_path(prefecture_id: @prefecture.id) %></p>
</div>
<% if @municipalities.present? %>
  <div class="search_municipality_link">
    <% @municipalities.each do |m| %>
      <span><%= link_to "#{m.name}", search_from_municipality_restaurants_path(municipality_id: m.id), class: 'link' %></span>
    <% end %>
  </div>
<% end %>

app/views/restaurants/index/_search_prefecture_link.html.erb
<div class="row search_prefecture_link">
  <div class="col-xs-12 area hokkaido">
    <p>北海道</p>
    <div class="prefecture_links">
      <%= link_to "北海道", get_search_municipality_link_restaurants_path(prefecture_id: 1), remote: true %>
    </div>
  </div>
  <div class="col-xs-12 area kanto">
    <p>関東</p>
    <div class="prefecture_links">
      <%= link_to "東京", get_search_municipality_link_restaurants_path(prefecture_id: 13), remote: true %>
      <%= link_to "茨城", get_search_municipality_link_restaurants_path(prefecture_id: 8), remote: true %>
      <%= link_to "栃木", get_search_municipality_link_restaurants_path(prefecture_id: 9), remote: true %>
      <%= link_to "群馬", get_search_municipality_link_restaurants_path(prefecture_id: 10), remote: true %>
      <%= link_to "埼玉", get_search_municipality_link_restaurants_path(prefecture_id: 11), remote: true %>
      <%= link_to "千葉", get_search_municipality_link_restaurants_path(prefecture_id: 12), remote: true %>
      <%= link_to "神奈川", get_search_municipality_link_restaurants_path(prefecture_id: 14), remote: true %>
    </div>
  </div>
  <div class="col-xs-12 area tohoku">
    <p>東北</p>
    <div class="prefecture_links">
      <%= link_to "青森", get_search_municipality_link_restaurants_path(prefecture_id: 2), remote: true %>
      <%= link_to "岩手", get_search_municipality_link_restaurants_path(prefecture_id: 3), remote: true %>
      <%= link_to "宮城", get_search_municipality_link_restaurants_path(prefecture_id: 4), remote: true %>
      <%= link_to "秋田", get_search_municipality_link_restaurants_path(prefecture_id: 5), remote: true %>
      <%= link_to "山形", get_search_municipality_link_restaurants_path(prefecture_id: 6), remote: true %>
      <%= link_to "福島", get_search_municipality_link_restaurants_path(prefecture_id: 7), remote: true %>
    </div>
  </div>
  <div class="col-xs-12 area tyubu">
    <p>中部</p>
    <div class="prefecture_links">
      <%= link_to "新潟", get_search_municipality_link_restaurants_path(prefecture_id: 15), remote: true %>
      <%= link_to "富山", get_search_municipality_link_restaurants_path(prefecture_id: 16), remote: true %>
      <%= link_to "石川", get_search_municipality_link_restaurants_path(prefecture_id: 17), remote: true %>
      <%= link_to "福井", get_search_municipality_link_restaurants_path(prefecture_id: 18), remote: true %>
      <%= link_to "山梨", get_search_municipality_link_restaurants_path(prefecture_id: 19), remote: true %>
      <%= link_to "長野", get_search_municipality_link_restaurants_path(prefecture_id: 20), remote: true %>
      <%= link_to "岐阜", get_search_municipality_link_restaurants_path(prefecture_id: 21), remote: true %>
      <%= link_to "静岡", get_search_municipality_link_restaurants_path(prefecture_id: 22), remote: true %>
      <%= link_to "愛知", get_search_municipality_link_restaurants_path(prefecture_id: 23), remote: true %>
    </div>
  </div>
  <div class="col-xs-12 area tyugoku">
    <p>中国</p>
    <div class="prefecture_links">
      <%= link_to "鳥取", get_search_municipality_link_restaurants_path(prefecture_id: 31), remote: true %>
      <%= link_to "島根", get_search_municipality_link_restaurants_path(prefecture_id: 32), remote: true %>
      <%= link_to "岡山", get_search_municipality_link_restaurants_path(prefecture_id: 33), remote: true %>
      <%= link_to "広島", get_search_municipality_link_restaurants_path(prefecture_id: 34), remote: true %>
      <%= link_to "山口", get_search_municipality_link_restaurants_path(prefecture_id: 35), remote: true %>
    </div>
  </div>
  <div class="col-xs-12 area kinki">
    <p>近畿</p>
    <div class="prefecture_links">
      <%= link_to "京都", get_search_municipality_link_restaurants_path(prefecture_id: 26), remote: true %>
      <%= link_to "大阪", get_search_municipality_link_restaurants_path(prefecture_id: 27), remote: true %>
      <%= link_to "三重", get_search_municipality_link_restaurants_path(prefecture_id: 24), remote: true %>
      <%= link_to "滋賀", get_search_municipality_link_restaurants_path(prefecture_id: 25), remote: true %>
      <%= link_to "兵庫", get_search_municipality_link_restaurants_path(prefecture_id: 28), remote: true %>
      <%= link_to "奈良", get_search_municipality_link_restaurants_path(prefecture_id: 29), remote: true %>
      <%= link_to "和歌山", get_search_municipality_link_restaurants_path(prefecture_id: 30), remote: true %>
    </div>
  </div>
  <div class="col-xs-12 area sikoku">
    <p>四国</p>
    <div class="prefecture_links">
      <%= link_to "徳島", get_search_municipality_link_restaurants_path(prefecture_id: 36), remote: true %>
      <%= link_to "香川", get_search_municipality_link_restaurants_path(prefecture_id: 37), remote: true %>
      <%= link_to "愛媛", get_search_municipality_link_restaurants_path(prefecture_id: 38), remote: true %>
      <%= link_to "高知", get_search_municipality_link_restaurants_path(prefecture_id: 39), remote: true %>
    </div>
  </div>
  <div class="col-xs-12 area kyusyu">
    <p>九州</p>
    <div class="prefecture_links">
      <%= link_to "福岡", get_search_municipality_link_restaurants_path(prefecture_id: 40), remote: true %>
      <%= link_to "佐賀", get_search_municipality_link_restaurants_path(prefecture_id: 41), remote: true %>
      <%= link_to "長崎", get_search_municipality_link_restaurants_path(prefecture_id: 42), remote: true %>
      <%= link_to "熊本", get_search_municipality_link_restaurants_path(prefecture_id: 43), remote: true %>
      <%= link_to "大分", get_search_municipality_link_restaurants_path(prefecture_id: 44), remote: true %>
      <%= link_to "宮崎", get_search_municipality_link_restaurants_path(prefecture_id: 45), remote: true %>
      <%= link_to "鹿児島", get_search_municipality_link_restaurants_path(prefecture_id: 46), remote: true %>
      <%= link_to "沖縄", get_search_municipality_link_restaurants_path(prefecture_id: 47), remote: true %>
    </div>
  </div>
</div>

app/views/restaurants/index/search_municipality_link.js.erb
$("#search_from_place_links").html("<%= escape_javascript(render('restaurants/index/search_municipality_link')) %>");

app/views/restaurants/index/search_prefecture_link.js.erb
$("#search_from_place_links").html("<%= escape_javascript(render('restaurants/index/search_prefecture_link')) %>");